### ISSUE TITLE
Distribute uncompressed slickback.js

### ISSUE THREAD

**Issue by lukateake** [teleological/slickback#1]
Please add an unpacked version of the slickback.js file to the dist directory in addition to the minify'ed one.  This will help speed up development.  Also, I place all my vendor scripts in a directory before concatenating and minifying them into a single script for the production application.

(I tried to build this project myself but there is an issue with buildr.npm [issue #8] that I can't quite get around.)

**Comment by teleological** [comment]
Uncompressed version is now included as: dist/slickback.full.js

I think buildr.npm issue 8 can be corrected by installing cson globally and setting NODE_PATH to the global node repository: The buildr command line script tries to require cson before any other buildr library is loaded. Please let me know if that works for you, and I will update buildr.npm issue 8.

Thanks!
