### ISSUE TITLE
require 2.0+ support?

### ISSUE THREAD

**Issue by lvanderbijl** [teleological/slickback#2]
I can't get slickback working "out of the box" with require2.0:

Uncaught TypeError: Cannot call method 'extend' of undefined backbone.slickback.js:63

Any ideas? I guess I could convert all the modules to require2.0 amds...

**Comment by lvanderbijl** [comment]
Fixed by adding Underscore to the module that loads slickgrid.

**Comment by teleological** [comment]
Thanks for letting me know you got it working. If you made any progress converting the modules to requirejs, I'd be glad to take a patch for that.

**Comment by lvanderbijl** [comment]
I might do that - though is there a reason you've modularised so extensively? I'm thinking if I do convert to amd modules, I'd probably only have:
Slickback
Slickback.Editors
Slickback.Formatters

At least that's what I'm thinking atm.

Any thoughts?

**Comment by lvanderbijl** [comment]
Ok, 

I've converted slickback to support amd and it works for me with Require 2.0+. I haven't (and won't have) had  a chance to test it in Node or using globals, but it _should_ work.

I'm happy to contribute the changes back but I've pretty much totally re-organised all the modules and functions so that they work as 3 modules: Slickback, Slickback.Editors and Slickback.Formatters. Though note I haven't changed ANY of the namespacing.

I put all the core functionality in Slickback. It includes all the mixins/collections etc (ie. Slickback.Collection etc).

Slickback.Editors and Slickback.Formatters are fairly self explanatory.

I don't know what the best way for me to get the 3 files to you is...

Let me know.

**Comment by lvanderbijl** [comment]
Ok, I forked this and added an amd directory with the files in: https://github.com/lvanderbijl/slickback/tree/master/amd

**Comment by feg624** [comment]
All: I'm pretty new with Require, Backbone, Underscore, SlickGrid and SlickBack. However I've made some advance in using all them together to display a table of about 5000 products for a project I'm involved into. The only thing I couldn't succeed is to use all these libraries with Require loaded modules, as I always get that Slickback variable is undefined, then I cannot use it to instantiate the collections.

Based on this thread, is there any possibility that Ivanderbijl can provide an example on how he/she made it work? I downloaded the AMD files from his depot, but I'm getting different errors now.

Thanks in advance,

Franco

**Comment by feg624** [comment]
It's me again, I just made a change on the slickback.js file with AMD definition to change "Backbone" to "backbone" on the define call, and it's working fine now. I made this as I have defined backbone module in lowercase on the rest of the application.

Thanks again,

Franco
